// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eloRun
NumericMatrix eloRun(NumericVector teamA, NumericVector teamB, NumericVector winsA, NumericVector k, NumericVector adjTeamA, NumericVector adjTeamB, NumericVector initialElo, int flag);
RcppExport SEXP _elo_eloRun(SEXP teamASEXP, SEXP teamBSEXP, SEXP winsASEXP, SEXP kSEXP, SEXP adjTeamASEXP, SEXP adjTeamBSEXP, SEXP initialEloSEXP, SEXP flagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type teamA(teamASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type teamB(teamBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type winsA(winsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjTeamA(adjTeamASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjTeamB(adjTeamBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialElo(initialEloSEXP);
    Rcpp::traits::input_parameter< int >::type flag(flagSEXP);
    rcpp_result_gen = Rcpp::wrap(eloRun(teamA, teamB, winsA, k, adjTeamA, adjTeamB, initialElo, flag));
    return rcpp_result_gen;
END_RCPP
}
// eloRunAsMatrix
NumericMatrix eloRunAsMatrix(NumericMatrix mat);
RcppExport SEXP _elo_eloRunAsMatrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(eloRunAsMatrix(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_elo_eloRun", (DL_FUNC) &_elo_eloRun, 8},
    {"_elo_eloRunAsMatrix", (DL_FUNC) &_elo_eloRunAsMatrix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_elo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
