// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eloRunAsMatrix
NumericMatrix eloRunAsMatrix(NumericMatrix mat, NumericVector initialElos, LogicalVector group);
RcppExport SEXP _elo_eloRunAsMatrix(SEXP matSEXP, SEXP initialElosSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialElos(initialElosSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(eloRunAsMatrix(mat, initialElos, group));
    return rcpp_result_gen;
END_RCPP
}
// eloRunRegressedAsMatrix
NumericMatrix eloRunRegressedAsMatrix(NumericMatrix mat, NumericVector initialElos, NumericMatrix regMat, LogicalVector regress, LogicalVector group);
RcppExport SEXP _elo_eloRunRegressedAsMatrix(SEXP matSEXP, SEXP initialElosSEXP, SEXP regMatSEXP, SEXP regressSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialElos(initialElosSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type regMat(regMatSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type regress(regressSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(eloRunRegressedAsMatrix(mat, initialElos, regMat, regress, group));
    return rcpp_result_gen;
END_RCPP
}
// eloColley
List eloColley(NumericMatrix teamA, NumericMatrix teamB, NumericVector winsA, NumericVector weightsA, NumericVector weightsB, NumericVector weights, NumericMatrix k, int nTeams);
RcppExport SEXP _elo_eloColley(SEXP teamASEXP, SEXP teamBSEXP, SEXP winsASEXP, SEXP weightsASEXP, SEXP weightsBSEXP, SEXP weightsSEXP, SEXP kSEXP, SEXP nTeamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type teamA(teamASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type teamB(teamBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type winsA(winsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsA(weightsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsB(weightsBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nTeams(nTeamsSEXP);
    rcpp_result_gen = Rcpp::wrap(eloColley(teamA, teamB, winsA, weightsA, weightsB, weights, k, nTeams));
    return rcpp_result_gen;
END_RCPP
}
// eloRun
List eloRun(NumericMatrix teamA, NumericMatrix teamB, NumericVector weightsA, NumericVector weightsB, NumericVector winsA, NumericMatrix k, NumericVector adjTeamA, NumericVector adjTeamB, LogicalVector regress, NumericVector to, double by, bool regressUnused, NumericVector initialElos, int flag);
RcppExport SEXP _elo_eloRun(SEXP teamASEXP, SEXP teamBSEXP, SEXP weightsASEXP, SEXP weightsBSEXP, SEXP winsASEXP, SEXP kSEXP, SEXP adjTeamASEXP, SEXP adjTeamBSEXP, SEXP regressSEXP, SEXP toSEXP, SEXP bySEXP, SEXP regressUnusedSEXP, SEXP initialElosSEXP, SEXP flagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type teamA(teamASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type teamB(teamBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsA(weightsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsB(weightsBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type winsA(winsASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjTeamA(adjTeamASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjTeamB(adjTeamBSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type regress(regressSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< double >::type by(bySEXP);
    Rcpp::traits::input_parameter< bool >::type regressUnused(regressUnusedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialElos(initialElosSEXP);
    Rcpp::traits::input_parameter< int >::type flag(flagSEXP);
    rcpp_result_gen = Rcpp::wrap(eloRun(teamA, teamB, weightsA, weightsB, winsA, k, adjTeamA, adjTeamB, regress, to, by, regressUnused, initialElos, flag));
    return rcpp_result_gen;
END_RCPP
}
// finalElos
NumericVector finalElos(NumericMatrix mat, int nTeams);
RcppExport SEXP _elo_finalElos(SEXP matSEXP, SEXP nTeamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type nTeams(nTeamsSEXP);
    rcpp_result_gen = Rcpp::wrap(finalElos(mat, nTeams));
    return rcpp_result_gen;
END_RCPP
}
// eloMarkovChain
List eloMarkovChain(NumericMatrix teamA, NumericMatrix teamB, NumericVector winsA, NumericVector weightsA, NumericVector weightsB, NumericVector weights, NumericMatrix k, int nTeams);
RcppExport SEXP _elo_eloMarkovChain(SEXP teamASEXP, SEXP teamBSEXP, SEXP winsASEXP, SEXP weightsASEXP, SEXP weightsBSEXP, SEXP weightsSEXP, SEXP kSEXP, SEXP nTeamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type teamA(teamASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type teamB(teamBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type winsA(winsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsA(weightsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsB(weightsBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nTeams(nTeamsSEXP);
    rcpp_result_gen = Rcpp::wrap(eloMarkovChain(teamA, teamB, winsA, weightsA, weightsB, weights, k, nTeams));
    return rcpp_result_gen;
END_RCPP
}
// eloWinPct
List eloWinPct(NumericVector winsA, NumericMatrix teamA, NumericMatrix teamB, NumericVector weightsA, NumericVector weightsB, NumericVector weights, int nTeams);
RcppExport SEXP _elo_eloWinPct(SEXP winsASEXP, SEXP teamASEXP, SEXP teamBSEXP, SEXP weightsASEXP, SEXP weightsBSEXP, SEXP weightsSEXP, SEXP nTeamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type winsA(winsASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type teamA(teamASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type teamB(teamBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsA(weightsASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightsB(weightsBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type nTeams(nTeamsSEXP);
    rcpp_result_gen = Rcpp::wrap(eloWinPct(winsA, teamA, teamB, weightsA, weightsB, weights, nTeams));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_elo_eloRunAsMatrix", (DL_FUNC) &_elo_eloRunAsMatrix, 3},
    {"_elo_eloRunRegressedAsMatrix", (DL_FUNC) &_elo_eloRunRegressedAsMatrix, 5},
    {"_elo_eloColley", (DL_FUNC) &_elo_eloColley, 8},
    {"_elo_eloRun", (DL_FUNC) &_elo_eloRun, 14},
    {"_elo_finalElos", (DL_FUNC) &_elo_finalElos, 2},
    {"_elo_eloMarkovChain", (DL_FUNC) &_elo_eloMarkovChain, 8},
    {"_elo_eloWinPct", (DL_FUNC) &_elo_eloWinPct, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_elo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
