# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eloRunAsMatrix <- function(mat, initialElos, group) {
    .Call('_elo_eloRunAsMatrix', PACKAGE = 'elo', mat, initialElos, group)
}

eloRunRegressedAsMatrix <- function(mat, initialElos, regMat, regress, group) {
    .Call('_elo_eloRunRegressedAsMatrix', PACKAGE = 'elo', mat, initialElos, regMat, regress, group)
}

eloRun <- function(teamA, teamB, winsA, k, adjTeamA, adjTeamB, regress, to, by, regressUnused, initialElos, flag) {
    .Call('_elo_eloRun', PACKAGE = 'elo', teamA, teamB, winsA, k, adjTeamA, adjTeamB, regress, to, by, regressUnused, initialElos, flag)
}

finalElos <- function(mat, nTeams) {
    .Call('_elo_finalElos', PACKAGE = 'elo', mat, nTeams)
}

