# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eloRun <- function(teamA, teamB, winsA, k, adjTeamA, adjTeamB, initialElo, flag) {
    .Call('_elo_eloRun', PACKAGE = 'elo', teamA, teamB, winsA, k, adjTeamA, adjTeamB, initialElo, flag)
}

eloRunAsMatrix <- function(mat) {
    .Call('_elo_eloRunAsMatrix', PACKAGE = 'elo', mat)
}

